[package]
name = "misto"
version = "0.1.0"
authors = ["Chris Fung <aergonaut@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = ">= 1.0.40", features = ["derive"] }
serde_json = ">= 1.0.40"
tera = { version = ">= 0.11.20", optional = true }
